name: Switch 新闻爬虫

on:
  schedule:
    - cron: '0 9 * * *'   # 每天早上 9 点执行
  workflow_dispatch:      # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          pip install -r requirements.txt

      - name: 运行爬虫脚本
        run: |
          python crawler.py

      - name: 提交变更
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # 检查是否有变更
          if [ -n "$(git diff --cached)" ]; then
            git commit -m "更新 Switch 新闻列表 $(date)"
            git remote set-url origin https://x-access-token:${{  secrets.REPO_PAT }}@github.com/${{ github.repository }}
            git push
          else
            echo "没有新变化，无需提交"
          fi
