name: Switch 新闻爬虫

on:
  schedule:
    - cron: '0 9 * * *'   # 每天早上 9 点执行
  workflow_dispatch:      # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          pip install -r requirements.txt
          

      - name: 测试 token 是否生效
        run: |
          curl -u :${{ secrets.REPO_PAT }} https://api.github.com/user 

          
      - name: 运行爬虫脚本
        run: |
          python crawler.py

      - name: 显示结果（调试用）
        run: |
          cat switch_news.md

      - name: 提交变更
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # 检查是否有更改
          git add results.json switch_news.md
          if [ -n "$(git diff --cached)" ]; then
            git commit -m "更新 Nintendo Switch 新闻 $(date)"
            git remote set-url origin https://x-access-token:${{  secrets.REPO_PAT }}@github.com/${{ github.repository }}
            git push
          else
            echo "没有新变化，无需提交"
          fi
